# Generated by Django 2.2.16 on 2022-07-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220707_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
